Hack: QuickFix: wrapp smoothscroller in a suspense to fix error
⨯ useSearchParams() should be wrapped in a suspense boundary at page
"/admindashboard". Read more:
https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout    at
o (/home/hknhmr/Frontend-next-js/.next/server/chunks/343.js:1:3580)
at d (/home/hknhmr/Frontend-next-js/.next/server/chunks/343.js:1:20104)
at o
(/home/hknhmr/Frontend-next-js/.next/server/app/admindashboard/page.js:1:14195)
at nO
(/home/hknhmr/Frontend-next-js/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:45959)
at nI
(/home/hknhmr/Frontend-next-js/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:47734)
at nI
(/home/hknhmr/Frontend-next-js/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:62515)
at nL
(/home/hknhmr/Frontend-next-js/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:65533)
at nN
(/home/hknhmr/Frontend-next-js/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63164)
at nB
(/home/hknhmr/Frontend-next-js/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:68946)
at nD
(/home/hknhmr/Frontend-next-js/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:67647)Error
occurred prerendering page "/admindashboard". Read more:
https://nextjs.org/docs/messages/prerender-errorExport encountered an
error on /admindashboard/page: /admindashboard, exiting the build.